version: "3"
services:
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    # mysqlの認証プラグインをmysql_native_passwordに変更
    command: --default-authentication-plugin=mysql_native_password
    # mysqlのデータ領域をホストにボリュームとしてマウントする
    volumes:
      - db-data:/var/lib/mysql

  app: &app_base
    build:
      context: backend
      dockerfile: ./containers/app/Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend/:/bean_stamp # ルートディレクトリをbindマウント
      - bundle:/usr/local/bundle
      - uploads:/bean_stamp/public/uploads # carrierwaveによる画像保存先をボリュームとしてマウント

    ports:
      - "3010:3000" # APIとしてホスト側は3010番ポートを開ける
    depends_on:
      - db
      - selenium_chrome
    stdin_open: true # -itオプションと同等の効果
    tty: true
    environment:
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
      WEBPACKER_DEV_SERVER_HOST: webpacker

  selenium_chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"
    logging:
      driver: none
    environment:
      CONNECTION_TIMEOUT: 600000

  webpacker:
    <<: *app_base
    command: bash -c "bundle exec bin/webpack-dev-server"
    depends_on:
      - app
    ports:
      - "3035:3035"
    tty: false
    stdin_open: false
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

volumes:
  db-data: {}
  uploads: {}
  bundle: {}
