version: "3"
services:
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    # mysqlの認証プラグインをmysql_native_passwordに変更
    command: --default-authentication-plugin=mysql_native_password
    # mysqlのデータ領域をホストにボリュームとしてマウントする
    volumes:
      - db-data:/var/lib/mysql

  app: &app_base
    build: .
    # rails server起動用
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # nginx -> puma用
    # command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/bean_stamp # カレントディレクトリをbindマウント
      - bundle:/usr/local/bundle
      - uploads:/bean_stamp/public/uploads # carrierwaveによる画像保存先をボリュームとしてマウント
      # - public-data:/bean_stamp/public # nginxと静的ページを共有
      # - tmp-data:/bean_stamp/tmp # nginxとのsocket通信に使用
      - ./tmp/screenshots:/bean_stamp/tmp/screenshots # systemテストのscreenshotをホスト環境で確認
      - log-data:/bean_stamp/log
      - ~/.ssh/bean-stamp:/root/.ssh # EC2インスタンス接続用の鍵を配置
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium_chrome
    stdin_open: true # -itオプションと同等の効果
    tty: true
    environment:
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
      WEBPACKER_DEV_SERVER_HOST: webpacker

  selenium_chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"
    logging:
      driver: none
    environment:
      CONNECTION_TIMEOUT: 600000

  webpacker:
    <<: *app_base
    command: bash -c "bundle exec bin/webpack-dev-server"
    depends_on:
      - app
    ports:
      - "3035:3035"
    tty: false
    stdin_open: false
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  # nginxをリバースプロキシとして使用する時に使用
  # web:
  #   build:
  #     context: containers/nginx
  #   volumes:
  #     - public-data:/bean_stamp/public
  #     - tmp-data:/bean_stamp/tmp
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - app

volumes:
  db-data: {}
  uploads: {}
  bundle: {}
  log-data: {}
  # public-data: {}
  # tmp-data: {}
