version: "3"
services:
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    # mysqlの認証プラグインをmysql_native_passwordに変更
    command: --default-authentication-plugin=mysql_native_password
    # mysqlのデータ領域をホストにボリュームとしてマウントする
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/beans_app # カレントディレクトリをbindマウント
      - rails-uploads:/beans_app/public/uploads # carrierwaveによる画像保存先をボリュームとしてマウント
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium_chrome
    stdin_open: true # -itオプションと同等の効果
    tty: true
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"
    logging:
      driver: none
    environment:
      CONNECTION_TIMEOUT: 600000
volumes:
  mysql-data: {}
  rails-uploads: {}
